# Generated by Django 4.2.6 on 2023-11-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='features',
            old_name='bathrooms',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='features',
            name='area',
        ),
        migrations.RemoveField(
            model_name='features',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='features',
            name='garages',
        ),
        migrations.AddField(
            model_name='features',
            name='description',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='houses',
            name='area',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='houses',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='houses',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='houses',
            name='garages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='features',
            name='amenities',
            field=models.ManyToManyField(to='main.amenity'),
        ),
    ]
